### ISSUE TITLE
TypeError: provider.send is not a function

### ISSUE THREAD

**Issue by shivamklr** [maticnetwork/maticjs-ethers#6]
I get an error for withdrawExit method. I would really appreciate if you could look into the code once and point me in the right direction.
`TypeError: provider.send is not a function
    at EtherWeb3Client.module.exports../src/ethers/web3_client.ts.EtherWeb3Client.getBlockWithTransaction (/home/..../node_modules/@maticnetwork/maticjs-ethers/dist/webpack:/matic-ethers/src/ethers/web3_client.ts:38:25)
    at /home/..../node_modules/@maticnetwork/maticjs/dist/webpack:/Matic/src/pos/exit_util.ts:202:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

[Link to Code](https://github.com/shivamklr/maticjs-sdk-demo/blob/3c7d9a341a80b151f67397f07c773d281a3dfd52/src/server.ts#L155)
`npm i` to install 
`npm run start:dev` to start the server

**Comment by shivamklr** [comment]
I wish to fix this issue. @ujjwalgupta94 @ujjwalguptaofficial Can we contribute to this project?

**Comment by ujjwalgupta94** [comment]
yeah sure @shivamklr , please do.

**Comment by shivamklr** [comment]
@ujjwalgupta94 I see that the project does not support **FallbackProvider** by ethers. Any plans to add support for that?
I figured out the issue, I created an ethers Wallet instance with the Fallback provider. However, on further investigation, I saw that the EthersClient only support JsonRPCProvider.

**Comment by ujjwalgupta94** [comment]
can you point out to some documentation, when do we need FallbackProvider @shivamklr ?
